# Generated by Django 5.2 on 2025-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truesaight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprocessing',
            name='processing_reference_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
