# Generated by Django 5.2 on 2025-04-09 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truesaight', '0002_videoprocessing_processing_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoprocessing',
            name='processing_reference_number',
        ),
    ]
